@extends('layouts.app')

@section('content')

<div class="panel">

    <!-- HEADER -->
    <div class="panel-header">

        <h4 class="mb-0">
            <i class="bi bi-plus-circle me-2"></i>
            Create Payroll
        </h4>

        <small class="text-muted">
            Select employee and payroll period — engine will calculate everything
        </small>

    </div>

    <!-- FORM -->
    <form action="{{ route('payroll.store') }}" method="POST">
        @csrf

        <div class="row">

            <!-- EMPLOYEE -->
            <div class="col-md-6 mb-3">

                <label class="form-label">Employee</label>

                <select name="employee_id" class="form-select" required>
                    <option value="">-- Select Employee --</option>

                    @foreach($employees as $employee)
                        <option value="{{ $employee->id }}">
                            {{ $employee->employee_id }}
                            - {{ $employee->first_name }} {{ $employee->last_name }}
                        </option>
                    @endforeach

                </select>

            </div>

            <!-- PAY PERIOD -->
            <div class="col-md-6 mb-3">

                <label class="form-label">Pay Period</label>

                <input type="month"
                       name="pay_period"
                       class="form-control"
                       required>

            </div>

        </div>

        <!-- INFO BOX -->
        <div class="alert alert-info">

            <strong>Note:</strong>
            Once created, payroll items (salary, tax, NAPSA, allowances) will be automatically generated by the Payroll Engine.

        </div>

        <!-- SUBMIT -->
        <button class="btn btn-primary">
            <i class="bi bi-cpu me-1"></i>
            Generate Payroll
        </button>

    </form>

</div>

@endsection